#!/usr/bin/env php
<?php

use csschecker\CssChecker;
use csschecker\reports\CheckstyleReport;
use csschecker\reports\CompositeReport;
use csschecker\reports\FileReport;
use csschecker\reports\Report;

require_once __DIR__ . '/vendor/autoload.php';

$args = $_SERVER['argv'];
unset($args[0]);

$checker = new CssChecker;
$report = new CompositeReport(array(
    new FileReport(fopen('php://stdout', 'w')),
    new FileReport(fopen(__DIR__ . '/result.txt', 'w')),
    new CheckstyleReport(__DIR__ . '/checkstyle.xml')
));

$checker->runChecks($args, $report);
