#!/usr/bin/env php
<?php
namespace csschecker;

use csschecker\reports\CheckstyleReport;
use csschecker\reports\CompositeReport;
use csschecker\reports\FileReport;
use csschecker\reports\Report;

require_once(__DIR__ . '/vendor/autoload.php');

$checks = array(
    'MultipleDefinitionsCheck' => array(
        'maxDefinitions' => 2
    ),
    'SelectorLengthCheck' => array(
        'maxSelectorLength' => 4
    ),
    'NoUsageCheck' => array()
);

$args = $_SERVER['argv'];
unset($args[0]);

$checker = new CssChecker;
$report = new CompositeReport(array(
    new FileReport(fopen('r', 'php://stdout')),
    new FileReport(fopen('r', __DIR__ . '/result.txt')),
    new CheckstyleReport(__DIR__ . '/checkstyle.xml')
));

$checker->runChecks($args, $checks, $report);
